# Generated by Django 5.2 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_data', '0049_mariadb_uuid_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriselearnerenrollment',
            name='course_passing_grade',
            field=models.FloatField(null=True),
        ),
    ]
